"use strict";
exports.__esModule = true;
var express_1 = require("express");
var path_1 = require("path");
var cookie_parser_1 = require("cookie-parser");
var index_1 = require("./routes/index");
var users_1 = require("./routes/users");
var cors_1 = require("cors");
var app = (0, express_1["default"])();
app.use((0, cors_1["default"])());
app.use(express_1["default"].json());
app.use(express_1["default"].urlencoded({ extended: false }));
app.use((0, cookie_parser_1["default"])());
app.use(express_1["default"].static(path_1["default"].join(__dirname, "public")));
app.use("/", index_1["default"]);
app.use("/users", users_1["default"]);
exports["default"] = app;
